### PR TITLE
scenario generator fixes

### PR DESCRIPTION
**Pull request by ilist2**
I finally got ScenarioGenerator working again also for ESS lattice.
- Main problem was that the semantics of sequences was implicitly changed - subsequence.position became the center instead of the beginning for cavities. Fixed it by making the semantics configurable through model/scenario generator configuration file. (It seemed nice to also add debug and divide magnets flags there)
- getParts and getPartsNr code was broken and fixed with nicer implementation
- There used to be marker with "BEGIN_sectionname". setStartId doesn't support to run probe from start of a section so I added workaround.
- If there was no "sequence" attribute in model configuration file, loading failed - fixed it for backwards compatibility
- Some other minor bugs

### CODE REVIEW

**Comment by ilist2** [comment]
Found another bug, ie: scenario generator silently ignores if there is an element sticking out of its section. But the generated lattice is longer than it should be. Fixed in those last two commits I submitted.

**Comment by Eothred** [comment]
I did not intend to reference this pull request. There is a parallel numbering of the pull requests we generate on our Bitbucket repository. This might potentially end up being confusing in the longer term I suppose.

**Comment by tapsns** [comment]
So, this isn't ready for merge. Is that correct? What action do you want me to take?

**Comment by ilist2** [comment]
On 14.3.2016 16:37, Tom Pelaia II wrote:

> So, this isn't ready for merge. Is that correct? What action do you want
> me to take?

No, it's ready. Please merge pull request #2.

**Comment by tapsns** [comment]
Okay, it builds and passes the unit tests, but when I run the unit tests I see several complaints such as the following:
Error: Elements do not fit sequence HEBT2 (element positions: [0.000000,131.160932], sequence position [0,131.053806])!

What does this error output mean? We don't see it in the master branch.

**Comment by dreadmill** [comment]
Ivo, do you see an obvious cause?

I will start digging into this later today as well.

**Comment by ilist2** [comment]
This is a new error/warning message if the elements don't fit the section.

Check the length of HEBT2 and the endpoint of last element in HEBT2.

   <sequence id="HEBT2" len="131.053806">

  <node type="DH" id="Ring_Mag:DH_A11" pos="130.690932" len="0.0" 
status="true">
        <attributes>
           <magnet len=".94" ...

130.690932+0.47/2 = 131.16

Elements do not fit sequence HEBT2 (element positions: 
[0.000000,131.160932], sequence position [0,131.053806])!

**Comment by dreadmill** [comment]
Thanks Ivo.  You had mentioned this earlier and I had forgotten, sorry about that.

Tom, this means that our database has errors (or inconsistencies) in it.

**Comment by tapsns** [comment]
Yes, we need to fix the issues with our optics. I've completed the pull request.

**Comment by tapsns** [comment]
Actually, I don't think this is an error. We need to be careful. The sequence lengths need to add up, but some elements can extend across boundaries of sequences as in this case. Extending the sequences would have side effects, so the error notice should probably be silenced as this is expected behavior. Maybe we can find a better way of dealing with this issue.

**Pull request merged**
